Fix caught signals check
sio2project/sio2jail pull request #31
Opened 2022-06-18 19:52 UTC by w0nsh

Hi.
The `caughtSignals` mask should be shifted by one, since the first bit corresponds to the signal with number 1.

2022-06-27 19:20 UTC, Michcioperz commented
I think I need another pair of eyes on this, but it does seem to make sense

2022-08-06 21:56 UTC, Wolf480pl approved these changes
Yup, tested and indeed the lowest bit of SigCgt mask corresponds to signal 1, not 0, at least on kernels 5.15 and 3.13.
The fix is correct, but it I think it needs a comment in the code explaining why we shift.

2022-08-06 21:57 UTC, Wolf480pl requested changes
The fix is correct but requires a comment in the code explaining why the shift.

2023-04-09 21:44 UTC, Wolf480pl approved these changes

2023-04-09 21:47 UTC, merged