Fix handling of rseq syscall
sio2project/sio2jail pull request #32
Opened 2022-10-02 15:12 UTC by A-dead-pixel

The current libseccomp in libseccomp.cmake (2.3.3 from 2018) was made for Linux v4.15-rc7 and doesn't know about the rseq (334) syscall, which seems to **always** be caught on my machine (kernel 5.19.12, Artix Linux) when using default options (just ``sio2jail -b dir:/ exe``).
If built with the old libseccomp, an exception is thrown, as we try to convert NULL to string when we can't resolve 334 to rseq. When we use a modern libseccomp, it is properly reported that we use a forbidden syscall.

So this pull request:
- adds a proper, descriptive exception for when libseccomp can't resolve the name of a syscall
- updates libseccomp in libseccomp.cmake
- adds rseq to the list of syscalls allowed by the default seccomp policy
- formats code with ``make clang-format``.

Additional question:
Who should I contact to request packaging sio2jail with this fix into a sandbox for sio2?

2022-10-02 19:06 UTC, Michcioperz commented
Hi, thanks for the PR. (Just for clarity I'm not properly involved with the project, but I'm curious about a few things.)

From what I remember old seccomp was used specifically because a newer version at the time of sio2jail's release had a drastic performance regression (I'm assuming @Wolf480pl might remember this better). So I imagine sending this to production would require some more testing.

What do you mean by saying it is "always caught on newer kernels"? Do you mean that any, however simple, C/C++ program triggers the error on newer kernels? (This would sound weird, I'd sooner expect this to be related to libc.)

2022-10-02 19:50 UTC, A-dead-pixel commented
Yes, even ``int main(){}`` causes the error.
You are right, the issue isn't caused by the kernel itself, but by a relatively new libc, which uses the syscall. If compiled in sio2's gcc 4.8.2 sandbox, it runs correctly. Also, from what I can see on the web, when executing on a kernel without support for it, rseq won't be used.
I'm guessing you meant the regression discussed on this [thread](https://github.com/seccomp/libseccomp/issues/153) and [PR](https://github.com/seccomp/libseccomp/pull/180), which seems to have been resolved in 2019.

2022-10-02 22:52 UTC, Michcioperz commented
Yeah, judging by the issue being authored by varqox, this is probably the right one.
FYI there exist newer sandboxes than the gcc 4.8.2 one http://downloads.sio2project.mimuw.edu.pl/sandboxes for instance the gcc 10.2 one seems to be used at this and last year's olympiads.

2023-04-01 19:18 UTC, Michcioperz requested changes

2023-04-01 19:18 UTC, Michcioperz commented on src/sio2jail.cc
Please don't mix multiple issue fixes into one PR

2023-04-01 19:26 UTC, closed without merging